server:
  port: 8080
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false

logging:
  level:
    root: WARN
    org:
      springframework:
        boot:
          web:
            embedded:
              tomcat:
                TomcatWebServer: INFO


spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Pierdole86
    initialization-mode: never






